# Generated by Django 4.2.25 on 2025-11-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='اسم المستخدم الفريد (عام لجميع الغرف)', max_length=100, unique=True, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, help_text='كلمة المرور للمستخدم في Matrix (مشفرة)', max_length=255, null=True, verbose_name='كلمة المرور')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل الآن')),
                ('is_banned', models.BooleanField(default=False, help_text='المستخدم المحظور لا يمكنه الدخول لأي غرفة', verbose_name='محظور')),
                ('is_moderator', models.BooleanField(default=False, help_text='المشرف يمكنه حذف الرسائل وحظر المستخدمين في جميع الغرف', verbose_name='مشرف')),
                ('matrix_user_id', models.CharField(blank=True, help_text='معرف المستخدم في Matrix (مثل: @user:domain.com)', max_length=255, null=True, unique=True, verbose_name='معرف مستخدم Matrix')),
                ('access_token', models.CharField(blank=True, help_text='Access Token للمصادقة في Matrix', max_length=500, null=True, verbose_name='رمز الوصول')),
                ('device_id', models.CharField(blank=True, help_text='معرف الجهاز في Matrix', max_length=255, null=True, verbose_name='معرف الجهاز')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية Access Token', null=True, verbose_name='انتهاء صلاحية الرمز')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('messages_count', models.IntegerField(default=0, help_text='عدد الرسائل التي أرسلها المستخدم في جميع الغرف', verbose_name='عدد الرسائل')),
            ],
            options={
                'verbose_name': 'مستخدم دردشة',
                'verbose_name_plural': 'مستخدمو الدردشة',
                'db_table': 'api_chatuser',
                'ordering': ['-is_online', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الغرفة (افتراضياً اسم القناة)', max_length=200, verbose_name='اسم الغرفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الغرفة')),
                ('is_active', models.BooleanField(default=True, help_text='عند التعطيل، لن يتمكن المستخدمون من الدخول', verbose_name='نشط')),
                ('max_users', models.IntegerField(default=100, help_text='الحد الأقصى لعدد المستخدمين في الغرفة', verbose_name='الحد الأقصى للمستخدمين')),
                ('matrix_room_id', models.CharField(blank=True, help_text='معرف الغرفة في سيرفر Matrix/Synapse', max_length=255, null=True, unique=True, verbose_name='معرف غرفة Matrix')),
                ('matrix_room_alias', models.CharField(blank=True, help_text='الاسم المستعار للغرفة في Matrix (مثل: #room:domain.com)', max_length=255, null=True, verbose_name='اسم مستعار للغرفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.OneToOneField(help_text='القناة المرتبطة بهذه الغرفة', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='streaming.livechannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'غرفة دردشة',
                'verbose_name_plural': 'غرف الدردشة',
                'db_table': 'api_chatroom',
                'ordering': ['channel__order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='اسم المستخدم الذي أرسل الرسالة', max_length=100, null=True, verbose_name='اسم المستخدم')),
                ('message_type', models.CharField(choices=[('message', 'رسالة عادية'), ('system', 'رسالة نظام'), ('user_joined', 'دخول مستخدم'), ('user_left', 'خروج مستخدم')], default='message', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('is_deleted', models.BooleanField(default=False, help_text='الرسائل المحذوفة لا تظهر للمستخدمين', verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='الغرفة')),
                ('user', models.ForeignKey(blank=True, help_text='مرجع اختياري للمستخدم إذا كان مسجلاً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.chatuser', verbose_name='المستخدم (مرجع)')),
            ],
            options={
                'verbose_name': 'رسالة دردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'db_table': 'api_chatmessage',
                'ordering': ['-created_at'],
            },
        ),
    ]
