# Generated by Django 4.2.25 on 2025-11-02 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الإعلان')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='صورة الإعلان')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الإعلان')),
                ('order', models.IntegerField(default=0, help_text='الرقم الأقل يظهر أولاً', verbose_name='ترتيب الإعلان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوكيل')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب الوكيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وكيل',
                'verbose_name_plural': 'الوكلاء',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الخبر')),
                ('order', models.IntegerField(default=0, help_text='الرقم الأقل يظهر أولاً', verbose_name='ترتيب الخبر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خبر الشريط',
                'verbose_name_plural': 'الشريط المتحرك',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الباقة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('time', models.CharField(help_text='مثل: 30 يوم، 3 أشهر، إلخ', max_length=100, verbose_name='الوقت')),
                ('download', models.CharField(help_text='مثل: غير محدود، 100 GB، إلخ', max_length=100, verbose_name='التحميل')),
                ('validity', models.CharField(help_text='مثل: صالح لمدة 30 يوم', max_length=100, verbose_name='الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب الباقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
