# Generated by Django 4.2.25 on 2025-11-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(default='شبكة MATCH LINK', max_length=200, verbose_name='اسم الشبكة')),
                ('logo', models.ImageField(blank=True, help_text='إذا لم يتم اختيار صورة، سيتم استخدام الشعار الافتراضي', null=True, upload_to='settings/', verbose_name='شعار الموقع')),
                ('admin_phone', models.CharField(default='779544414', max_length=50, verbose_name='رقم الإدارة')),
                ('repair_phone', models.CharField(default='779544414', max_length=50, verbose_name='رقم الصيانة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
