# Generated by Django 4.2.25 on 2025-11-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الرابط')),
                ('url', models.URLField(max_length=500, verbose_name='رابط الرابط')),
                ('icon', models.ImageField(upload_to='links/icons/', verbose_name='أيقونة الرابط')),
                ('order', models.IntegerField(default=0, help_text='الرقم الأقل يظهر أولاً', verbose_name='ترتيب الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رابط',
                'verbose_name_plural': 'الروابط',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
