# Generated by Django 4.2.25 on 2025-11-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_customer_login',
            field=models.BooleanField(default=False, help_text="عند التفعيل، سيظهر زر 'الدخول كمشترك' أسفل زر تسجيل الدخول", verbose_name='تفعيل لوحة دخول المشترك'),
        ),
    ]
