# Generated by Django 4.2.25 on 2025-11-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sitesettings_enable_customer_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القناة')),
                ('stream_url', models.URLField(max_length=500, verbose_name='رابط البث')),
                ('stream_type', models.CharField(choices=[('flv', 'FLV'), ('hls', 'HLS'), ('mpegts', 'MPEG-TS'), ('dash', 'DASH'), ('html5', 'HTML5')], default='hls', max_length=10, verbose_name='نوع البث')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='channels/icons/', verbose_name='أيقونة القناة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القناة')),
                ('order', models.IntegerField(default=0, help_text='الرقم الأقل يظهر أولاً', verbose_name='ترتيب القناة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قناة بث مباشر',
                'verbose_name_plural': 'قنوات البث المباشر',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=200, verbose_name='اسم الفريق الأول')),
                ('team1_logo', models.ImageField(blank=True, null=True, upload_to='matches/teams/', verbose_name='شعار الفريق الأول')),
                ('team2_name', models.CharField(max_length=200, verbose_name='اسم الفريق الثاني')),
                ('team2_logo', models.ImageField(blank=True, null=True, upload_to='matches/teams/', verbose_name='شعار الفريق الثاني')),
                ('match_time', models.DateTimeField(verbose_name='وقت المباراة')),
                ('channel', models.CharField(blank=True, help_text='اسم القناة التي ستنقل المباراة', max_length=200, null=True, verbose_name='القناة الناقلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب المباراة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('live_channel', models.ForeignKey(blank=True, help_text='القناة المرتبطة من قنوات البث المباشر', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.livechannel', verbose_name='قناة البث المباشر')),
            ],
            options={
                'verbose_name': 'مباراة',
                'verbose_name_plural': 'المواجهات',
                'ordering': ['match_time', 'order'],
            },
        ),
    ]
