# Generated by Django 4.2.25 on 2025-11-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_livechannel_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_chat',
            field=models.BooleanField(default=False, help_text='عند التفعيل، سيظهر زر الدردشة في صفحة البث المباشر', verbose_name='تفعيل خدمة الدردشة'),
        ),
    ]
