# Generated by Django 4.2.25 on 2025-11-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sitesettings_enable_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الغرفة (افتراضياً اسم القناة)', max_length=200, verbose_name='اسم الغرفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الغرفة')),
                ('is_active', models.BooleanField(default=True, help_text='عند التعطيل، لن يتمكن المستخدمون من الدخول', verbose_name='نشط')),
                ('max_users', models.IntegerField(default=100, help_text='الحد الأقصى لعدد المستخدمين في الغرفة', verbose_name='الحد الأقصى للمستخدمين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.OneToOneField(help_text='القناة المرتبطة بهذه الغرفة', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='api.livechannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'غرفة دردشة',
                'verbose_name_plural': 'غرف الدردشة',
                'ordering': ['channel__order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='اسم المستخدم')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل الآن')),
                ('is_banned', models.BooleanField(default=False, help_text='المستخدم المحظور لا يمكنه الدخول', verbose_name='محظور')),
                ('is_moderator', models.BooleanField(default=False, help_text='المشرف يمكنه حذف الرسائل وحظر المستخدمين', verbose_name='مشرف')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('messages_count', models.IntegerField(default=0, help_text='عدد الرسائل التي أرسلها المستخدم', verbose_name='عدد الرسائل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.chatroom', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'مستخدم دردشة',
                'verbose_name_plural': 'مستخدمو الدردشة',
                'ordering': ['-is_online', '-last_seen'],
                'unique_together': {('username', 'room')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('message', 'رسالة عادية'), ('system', 'رسالة نظام'), ('user_joined', 'دخول مستخدم'), ('user_left', 'خروج مستخدم')], default='message', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('is_deleted', models.BooleanField(default=False, help_text='الرسائل المحذوفة لا تظهر للمستخدمين', verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom', verbose_name='الغرفة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.chatuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة دردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'ordering': ['-created_at'],
            },
        ),
    ]
