# Generated by Django 4.2.25 on 2025-11-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatroom_chatuser_chatmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='username',
            field=models.CharField(blank=True, help_text='اسم المستخدم الذي أرسل الرسالة', max_length=100, null=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='مرجع اختياري للمستخدم إذا كان مسجلاً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.chatuser', verbose_name='المستخدم (مرجع)'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='المستخدم المحظور لا يمكنه الدخول لأي غرفة', verbose_name='محظور'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='المشرف يمكنه حذف الرسائل وحظر المستخدمين في جميع الغرف', verbose_name='مشرف'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='messages_count',
            field=models.IntegerField(default=0, help_text='عدد الرسائل التي أرسلها المستخدم في جميع الغرف', verbose_name='عدد الرسائل'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(help_text='اسم المستخدم الفريد (عام لجميع الغرف)', max_length=100, unique=True, verbose_name='اسم المستخدم'),
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='room',
        ),
    ]
