# Generated by Django 4.2.25 on 2025-11-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_chatuser_unique_together_chatmessage_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='matrix_room_alias',
            field=models.CharField(blank=True, help_text='الاسم المستعار للغرفة في Matrix (مثل: #room:domain.com)', max_length=255, null=True, verbose_name='اسم مستعار للغرفة'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='matrix_room_id',
            field=models.CharField(blank=True, help_text='معرف الغرفة في سيرفر Matrix/Synapse', max_length=255, null=True, unique=True, verbose_name='معرف غرفة Matrix'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access Token للمصادقة في Matrix', max_length=500, null=True, verbose_name='رمز الوصول'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='device_id',
            field=models.CharField(blank=True, help_text='معرف الجهاز في Matrix', max_length=255, null=True, verbose_name='معرف الجهاز'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='matrix_user_id',
            field=models.CharField(blank=True, help_text='معرف المستخدم في Matrix (مثل: @user:domain.com)', max_length=255, null=True, unique=True, verbose_name='معرف مستخدم Matrix'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية Access Token', null=True, verbose_name='انتهاء صلاحية الرمز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='matrix_admin_password',
            field=models.CharField(blank=True, help_text='كلمة مرور مستخدم الإدارة (يُنصح بتخزينها بشكل آمن)', max_length=200, null=True, verbose_name='كلمة مرور إدارة Matrix'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='matrix_admin_user',
            field=models.CharField(blank=True, help_text='اسم مستخدم الإدارة في Matrix (لإنشاء الغرف)', max_length=200, null=True, verbose_name='مستخدم إدارة Matrix'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='matrix_homeserver_url',
            field=models.URLField(blank=True, help_text='عنوان سيرفر Matrix/Synapse (مثال: http://172.16.1.2:8008)', null=True, verbose_name='عنوان سيرفر Matrix'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='matrix_room_prefix',
            field=models.CharField(default='match_channel_', help_text='البادئة المستخدمة في أسماء غرف Matrix', max_length=50, verbose_name='بادئة أسماء الغرف'),
        ),
    ]
