# Generated by Django 4.2.25 on 2025-11-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatroom_matrix_room_alias_chatroom_matrix_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='matrix_space_id',
            field=models.CharField(blank=True, help_text='معرف Space (المجموعة) الرئيسي في Matrix الذي يحتوي على جميع الغرف', max_length=255, null=True, verbose_name='معرف Space الرئيسي'),
        ),
    ]
