# Generated by Django 4.2.25 on 2025-11-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_matrix_space_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='password',
            field=models.CharField(blank=True, help_text='كلمة المرور للمستخدم في Matrix (مشفرة)', max_length=255, null=True, verbose_name='كلمة المرور'),
        ),
    ]
