# Generated by Django 4.2.25 on 2025-11-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_time', 'order'], 'verbose_name': 'مباراة', 'verbose_name_plural': 'الموجهات'},
        ),
    ]
