# Generated by Django 4.2.25 on 2025-11-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(default='شبكة MATCH LINK', max_length=200, verbose_name='اسم الشبكة')),
                ('logo', models.ImageField(blank=True, help_text='إذا لم يتم اختيار صورة، سيتم استخدام الشعار الافتراضي', null=True, upload_to='settings/', verbose_name='شعار الموقع')),
                ('admin_phone', models.CharField(default='779544414', max_length=50, verbose_name='رقم الإدارة')),
                ('repair_phone', models.CharField(default='779544414', max_length=50, verbose_name='رقم الصيانة')),
                ('enable_customer_login', models.BooleanField(default=False, help_text="عند التفعيل، سيظهر زر 'الدخول كمشترك' أسفل زر تسجيل الدخول", verbose_name='تفعيل لوحة دخول المشترك')),
                ('enable_chat', models.BooleanField(default=False, help_text='عند التفعيل، سيظهر زر الدردشة في صفحة البث المباشر', verbose_name='تفعيل خدمة الدردشة')),
                ('matrix_homeserver_url', models.URLField(blank=True, help_text='عنوان سيرفر Matrix/Synapse (مثال: http://172.16.1.2:8008)', null=True, verbose_name='عنوان سيرفر Matrix')),
                ('matrix_admin_user', models.CharField(blank=True, help_text='اسم مستخدم الإدارة في Matrix (لإنشاء الغرف)', max_length=200, null=True, verbose_name='مستخدم إدارة Matrix')),
                ('matrix_admin_password', models.CharField(blank=True, help_text='كلمة مرور مستخدم الإدارة (يُنصح بتخزينها بشكل آمن)', max_length=200, null=True, verbose_name='كلمة مرور إدارة Matrix')),
                ('matrix_room_prefix', models.CharField(default='match_channel_', help_text='البادئة المستخدمة في أسماء غرف Matrix', max_length=50, verbose_name='بادئة أسماء الغرف')),
                ('matrix_space_id', models.CharField(blank=True, help_text='معرف Space (المجموعة) الرئيسي في Matrix الذي يحتوي على جميع الغرف', max_length=255, null=True, verbose_name='معرف Space الرئيسي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
                'db_table': 'api_sitesettings',
            },
        ),
    ]
